language: android

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - platform-tools
    - tools
    - build-tools-26.0.1
    - android-26

jdk:
  - oraclejdk8

script:
  ./gradlew build
